apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orbit.fullname" . }}-scenarios
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orbit.labels" . | nindent 4 }}
data:
  scenarios.yaml: |
    activeScenario: {{ .Values.config.activeScenario | default "" | quote }}
    stabilizationPeriod: {{ .Values.config.stabilizationPeriod | default "10s" | quote }}
    scenarios:
      {{- toYaml .Values.scenarios | nindent 6 }}
    {{- with .Values.northSouth.satellites }}
    satellites:
      {{- toYaml . | nindent 6 }}
    {{- end }}
