{{- if and (not .Values.auth.existingSecret) .Values.auth.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orbit.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.auth.token | b64enc | quote }}
{{- end }}
