// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/orbit/v1/orbit.proto

package orbitv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrbitService_Echo_FullMethodName           = "/orbit.v1.OrbitService/Echo"
	OrbitService_Register_FullMethodName       = "/orbit.v1.OrbitService/Register"
	OrbitService_AssignSchedule_FullMethodName = "/orbit.v1.OrbitService/AssignSchedule"
	OrbitService_ReportStatus_FullMethodName   = "/orbit.v1.OrbitService/ReportStatus"
	OrbitService_StreamData_FullMethodName     = "/orbit.v1.OrbitService/StreamData"
)

// OrbitServiceClient is the client API for OrbitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrbitServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	Register(ctx context.Context, in *PeerRegistration, opts ...grpc.CallOption) (*PeerRegistrationResponse, error)
	AssignSchedule(ctx context.Context, in *ProbeSchedule, opts ...grpc.CallOption) (*ProbeScheduleResponse, error)
	ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusReportResponse, error)
	StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, DataChunk], error)
}

type orbitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrbitServiceClient(cc grpc.ClientConnInterface) OrbitServiceClient {
	return &orbitServiceClient{cc}
}

func (c *orbitServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, OrbitService_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitServiceClient) Register(ctx context.Context, in *PeerRegistration, opts ...grpc.CallOption) (*PeerRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerRegistrationResponse)
	err := c.cc.Invoke(ctx, OrbitService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitServiceClient) AssignSchedule(ctx context.Context, in *ProbeSchedule, opts ...grpc.CallOption) (*ProbeScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeScheduleResponse)
	err := c.cc.Invoke(ctx, OrbitService_AssignSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitServiceClient) ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReportResponse)
	err := c.cc.Invoke(ctx, OrbitService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitServiceClient) StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrbitService_ServiceDesc.Streams[0], OrbitService_StreamData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, DataChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbitService_StreamDataClient = grpc.BidiStreamingClient[DataChunk, DataChunk]

// OrbitServiceServer is the server API for OrbitService service.
// All implementations must embed UnimplementedOrbitServiceServer
// for forward compatibility.
type OrbitServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	Register(context.Context, *PeerRegistration) (*PeerRegistrationResponse, error)
	AssignSchedule(context.Context, *ProbeSchedule) (*ProbeScheduleResponse, error)
	ReportStatus(context.Context, *StatusReport) (*StatusReportResponse, error)
	StreamData(grpc.BidiStreamingServer[DataChunk, DataChunk]) error
	mustEmbedUnimplementedOrbitServiceServer()
}

// UnimplementedOrbitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrbitServiceServer struct{}

func (UnimplementedOrbitServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedOrbitServiceServer) Register(context.Context, *PeerRegistration) (*PeerRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedOrbitServiceServer) AssignSchedule(context.Context, *ProbeSchedule) (*ProbeScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignSchedule not implemented")
}
func (UnimplementedOrbitServiceServer) ReportStatus(context.Context, *StatusReport) (*StatusReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedOrbitServiceServer) StreamData(grpc.BidiStreamingServer[DataChunk, DataChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedOrbitServiceServer) mustEmbedUnimplementedOrbitServiceServer() {}
func (UnimplementedOrbitServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrbitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrbitServiceServer will
// result in compilation errors.
type UnsafeOrbitServiceServer interface {
	mustEmbedUnimplementedOrbitServiceServer()
}

func RegisterOrbitServiceServer(s grpc.ServiceRegistrar, srv OrbitServiceServer) {
	// If the following call panics, it indicates UnimplementedOrbitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrbitService_ServiceDesc, srv)
}

func _OrbitService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitService_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitServiceServer).Register(ctx, req.(*PeerRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitService_AssignSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeSchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitServiceServer).AssignSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitService_AssignSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitServiceServer).AssignSchedule(ctx, req.(*ProbeSchedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitServiceServer).ReportStatus(ctx, req.(*StatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitService_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrbitServiceServer).StreamData(&grpc.GenericServerStream[DataChunk, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbitService_StreamDataServer = grpc.BidiStreamingServer[DataChunk, DataChunk]

// OrbitService_ServiceDesc is the grpc.ServiceDesc for OrbitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrbitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbit.v1.OrbitService",
	HandlerType: (*OrbitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _OrbitService_Echo_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _OrbitService_Register_Handler,
		},
		{
			MethodName: "AssignSchedule",
			Handler:    _OrbitService_AssignSchedule_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _OrbitService_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _OrbitService_StreamData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/orbit/v1/orbit.proto",
}
