// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/orbit/v1/orbit.proto

package orbitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoRequest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *EchoRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	ResponderId   string                 `protobuf:"bytes,4,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *EchoResponse) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *EchoResponse) GetResponderId() string {
	if x != nil {
		return x.ResponderId
	}
	return ""
}

type PeerRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Zone          string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRegistration) Reset() {
	*x = PeerRegistration{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRegistration) ProtoMessage() {}

func (x *PeerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRegistration.ProtoReflect.Descriptor instead.
func (*PeerRegistration) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{2}
}

func (x *PeerRegistration) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerRegistration) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerRegistration) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PeerRegistration) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PeerRegistration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PeerRegistration) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type PeerRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRegistrationResponse) Reset() {
	*x = PeerRegistrationResponse{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRegistrationResponse) ProtoMessage() {}

func (x *PeerRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRegistrationResponse.ProtoReflect.Descriptor instead.
func (*PeerRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{3}
}

func (x *PeerRegistrationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PeerRegistrationResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type FlowSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TargetAddress        string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TargetPort           int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Direction            string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	BandwidthBps         int64                  `protobuf:"varint,10,opt,name=bandwidth_bps,json=bandwidthBps,proto3" json:"bandwidth_bps,omitempty"`
	PacketRate           int32                  `protobuf:"varint,11,opt,name=packet_rate,json=packetRate,proto3" json:"packet_rate,omitempty"`
	PacketSize           int32                  `protobuf:"varint,12,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	Rps                  int32                  `protobuf:"varint,13,opt,name=rps,proto3" json:"rps,omitempty"`
	PayloadBytes         int32                  `protobuf:"varint,14,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	Connections          int32                  `protobuf:"varint,15,opt,name=connections,proto3" json:"connections,omitempty"`
	HttpMethod           string                 `protobuf:"bytes,16,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	KeepAlive            bool                   `protobuf:"varint,17,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	Pattern              string                 `protobuf:"bytes,18,opt,name=pattern,proto3" json:"pattern,omitempty"`
	BurstDurationSeconds int32                  `protobuf:"varint,19,opt,name=burst_duration_seconds,json=burstDurationSeconds,proto3" json:"burst_duration_seconds,omitempty"`
	BurstIntervalSeconds int32                  `protobuf:"varint,20,opt,name=burst_interval_seconds,json=burstIntervalSeconds,proto3" json:"burst_interval_seconds,omitempty"`
	ConnectionsPerSecond int32                  `protobuf:"varint,21,opt,name=connections_per_second,json=connectionsPerSecond,proto3" json:"connections_per_second,omitempty"`
	HoldDurationMs       int32                  `protobuf:"varint,22,opt,name=hold_duration_ms,json=holdDurationMs,proto3" json:"hold_duration_ms,omitempty"`
	Duration             *durationpb.Duration   `protobuf:"bytes,30,opt,name=duration,proto3" json:"duration,omitempty"`
	Interval             *durationpb.Duration   `protobuf:"bytes,31,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FlowSpec) Reset() {
	*x = FlowSpec{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSpec) ProtoMessage() {}

func (x *FlowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSpec.ProtoReflect.Descriptor instead.
func (*FlowSpec) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{4}
}

func (x *FlowSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlowSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlowSpec) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *FlowSpec) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *FlowSpec) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FlowSpec) GetBandwidthBps() int64 {
	if x != nil {
		return x.BandwidthBps
	}
	return 0
}

func (x *FlowSpec) GetPacketRate() int32 {
	if x != nil {
		return x.PacketRate
	}
	return 0
}

func (x *FlowSpec) GetPacketSize() int32 {
	if x != nil {
		return x.PacketSize
	}
	return 0
}

func (x *FlowSpec) GetRps() int32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *FlowSpec) GetPayloadBytes() int32 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

func (x *FlowSpec) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *FlowSpec) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *FlowSpec) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

func (x *FlowSpec) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FlowSpec) GetBurstDurationSeconds() int32 {
	if x != nil {
		return x.BurstDurationSeconds
	}
	return 0
}

func (x *FlowSpec) GetBurstIntervalSeconds() int32 {
	if x != nil {
		return x.BurstIntervalSeconds
	}
	return 0
}

func (x *FlowSpec) GetConnectionsPerSecond() int32 {
	if x != nil {
		return x.ConnectionsPerSecond
	}
	return 0
}

func (x *FlowSpec) GetHoldDurationMs() int32 {
	if x != nil {
		return x.HoldDurationMs
	}
	return 0
}

func (x *FlowSpec) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *FlowSpec) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

type ProbeSchedule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScenarioName    string                 `protobuf:"bytes,1,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	EastWestFlows   []*FlowSpec            `protobuf:"bytes,3,rep,name=east_west_flows,json=eastWestFlows,proto3" json:"east_west_flows,omitempty"`
	NorthSouthFlows []*FlowSpec            `protobuf:"bytes,4,rep,name=north_south_flows,json=northSouthFlows,proto3" json:"north_south_flows,omitempty"`
	StartAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProbeSchedule) Reset() {
	*x = ProbeSchedule{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSchedule) ProtoMessage() {}

func (x *ProbeSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSchedule.ProtoReflect.Descriptor instead.
func (*ProbeSchedule) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{5}
}

func (x *ProbeSchedule) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *ProbeSchedule) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProbeSchedule) GetEastWestFlows() []*FlowSpec {
	if x != nil {
		return x.EastWestFlows
	}
	return nil
}

func (x *ProbeSchedule) GetNorthSouthFlows() []*FlowSpec {
	if x != nil {
		return x.NorthSouthFlows
	}
	return nil
}

func (x *ProbeSchedule) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

type ProbeScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeScheduleResponse) Reset() {
	*x = ProbeScheduleResponse{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeScheduleResponse) ProtoMessage() {}

func (x *ProbeScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeScheduleResponse.ProtoReflect.Descriptor instead.
func (*ProbeScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeScheduleResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ProbeScheduleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ScenarioName  string                 `protobuf:"bytes,2,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ActiveFlows   int32                  `protobuf:"varint,4,opt,name=active_flows,json=activeFlows,proto3" json:"active_flows,omitempty"`
	BytesSent     map[string]int64       `protobuf:"bytes,5,rep,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BytesReceived map[string]int64       `protobuf:"bytes,6,rep,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ReportedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{7}
}

func (x *StatusReport) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *StatusReport) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *StatusReport) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StatusReport) GetActiveFlows() int32 {
	if x != nil {
		return x.ActiveFlows
	}
	return 0
}

func (x *StatusReport) GetBytesSent() map[string]int64 {
	if x != nil {
		return x.BytesSent
	}
	return nil
}

func (x *StatusReport) GetBytesReceived() map[string]int64 {
	if x != nil {
		return x.BytesReceived
	}
	return nil
}

func (x *StatusReport) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

type StatusReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReportResponse) Reset() {
	*x = StatusReportResponse{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReportResponse) ProtoMessage() {}

func (x *StatusReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReportResponse.ProtoReflect.Descriptor instead.
func (*StatusReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{8}
}

func (x *StatusReportResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orbit_v1_orbit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_proto_orbit_v1_orbit_proto_rawDescGZIP(), []int{9}
}

func (x *DataChunk) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *DataChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataChunk) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DataChunk) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *DataChunk) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

var File_proto_orbit_v1_orbit_proto protoreflect.FileDescriptor

const file_proto_orbit_v1_orbit_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/orbit/v1/orbit.proto\x12\borbit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"y\n" +
	"\vEchoRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\"\xbd\x01\n" +
	"\fEchoResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12!\n" +
	"\fresponder_id\x18\x04 \x01(\tR\vresponderId\"\xae\x01\n" +
	"\x10PeerRegistration\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\"S\n" +
	"\x18PeerRegistrationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\"\xe8\x05\n" +
	"\bFlowSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12#\n" +
	"\rbandwidth_bps\x18\n" +
	" \x01(\x03R\fbandwidthBps\x12\x1f\n" +
	"\vpacket_rate\x18\v \x01(\x05R\n" +
	"packetRate\x12\x1f\n" +
	"\vpacket_size\x18\f \x01(\x05R\n" +
	"packetSize\x12\x10\n" +
	"\x03rps\x18\r \x01(\x05R\x03rps\x12#\n" +
	"\rpayload_bytes\x18\x0e \x01(\x05R\fpayloadBytes\x12 \n" +
	"\vconnections\x18\x0f \x01(\x05R\vconnections\x12\x1f\n" +
	"\vhttp_method\x18\x10 \x01(\tR\n" +
	"httpMethod\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x11 \x01(\bR\tkeepAlive\x12\x18\n" +
	"\apattern\x18\x12 \x01(\tR\apattern\x124\n" +
	"\x16burst_duration_seconds\x18\x13 \x01(\x05R\x14burstDurationSeconds\x124\n" +
	"\x16burst_interval_seconds\x18\x14 \x01(\x05R\x14burstIntervalSeconds\x124\n" +
	"\x16connections_per_second\x18\x15 \x01(\x05R\x14connectionsPerSecond\x12(\n" +
	"\x10hold_duration_ms\x18\x16 \x01(\x05R\x0eholdDurationMs\x125\n" +
	"\bduration\x18\x1e \x01(\v2\x19.google.protobuf.DurationR\bduration\x125\n" +
	"\binterval\x18\x1f \x01(\v2\x19.google.protobuf.DurationR\binterval\"\xfe\x01\n" +
	"\rProbeSchedule\x12#\n" +
	"\rscenario_name\x18\x01 \x01(\tR\fscenarioName\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12:\n" +
	"\x0feast_west_flows\x18\x03 \x03(\v2\x12.orbit.v1.FlowSpecR\reastWestFlows\x12>\n" +
	"\x11north_south_flows\x18\x04 \x03(\v2\x12.orbit.v1.FlowSpecR\x0fnorthSouthFlows\x125\n" +
	"\bstart_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\"I\n" +
	"\x15ProbeScheduleResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xdb\x03\n" +
	"\fStatusReport\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12#\n" +
	"\rscenario_name\x18\x02 \x01(\tR\fscenarioName\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12!\n" +
	"\factive_flows\x18\x04 \x01(\x05R\vactiveFlows\x12D\n" +
	"\n" +
	"bytes_sent\x18\x05 \x03(\v2%.orbit.v1.StatusReport.BytesSentEntryR\tbytesSent\x12P\n" +
	"\x0ebytes_received\x18\x06 \x03(\v2).orbit.v1.StatusReport.BytesReceivedEntryR\rbytesReceived\x12;\n" +
	"\vreported_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\x1a<\n" +
	"\x0eBytesSentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a@\n" +
	"\x12BytesReceivedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\":\n" +
	"\x14StatusReportResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xab\x01\n" +
	"\tDataChunk\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x123\n" +
	"\asent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\fR\bchecksum2\xe1\x02\n" +
	"\fOrbitService\x125\n" +
	"\x04Echo\x12\x15.orbit.v1.EchoRequest\x1a\x16.orbit.v1.EchoResponse\x12J\n" +
	"\bRegister\x12\x1a.orbit.v1.PeerRegistration\x1a\".orbit.v1.PeerRegistrationResponse\x12J\n" +
	"\x0eAssignSchedule\x12\x17.orbit.v1.ProbeSchedule\x1a\x1f.orbit.v1.ProbeScheduleResponse\x12F\n" +
	"\fReportStatus\x12\x16.orbit.v1.StatusReport\x1a\x1e.orbit.v1.StatusReportResponse\x12:\n" +
	"\n" +
	"StreamData\x12\x13.orbit.v1.DataChunk\x1a\x13.orbit.v1.DataChunk(\x010\x01B1Z/github.com/daxroc/orbit/proto/orbit/v1;orbitv1b\x06proto3"

var (
	file_proto_orbit_v1_orbit_proto_rawDescOnce sync.Once
	file_proto_orbit_v1_orbit_proto_rawDescData []byte
)

func file_proto_orbit_v1_orbit_proto_rawDescGZIP() []byte {
	file_proto_orbit_v1_orbit_proto_rawDescOnce.Do(func() {
		file_proto_orbit_v1_orbit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orbit_v1_orbit_proto_rawDesc), len(file_proto_orbit_v1_orbit_proto_rawDesc)))
	})
	return file_proto_orbit_v1_orbit_proto_rawDescData
}

var file_proto_orbit_v1_orbit_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_orbit_v1_orbit_proto_goTypes = []any{
	(*EchoRequest)(nil),              // 0: orbit.v1.EchoRequest
	(*EchoResponse)(nil),             // 1: orbit.v1.EchoResponse
	(*PeerRegistration)(nil),         // 2: orbit.v1.PeerRegistration
	(*PeerRegistrationResponse)(nil), // 3: orbit.v1.PeerRegistrationResponse
	(*FlowSpec)(nil),                 // 4: orbit.v1.FlowSpec
	(*ProbeSchedule)(nil),            // 5: orbit.v1.ProbeSchedule
	(*ProbeScheduleResponse)(nil),    // 6: orbit.v1.ProbeScheduleResponse
	(*StatusReport)(nil),             // 7: orbit.v1.StatusReport
	(*StatusReportResponse)(nil),     // 8: orbit.v1.StatusReportResponse
	(*DataChunk)(nil),                // 9: orbit.v1.DataChunk
	nil,                              // 10: orbit.v1.StatusReport.BytesSentEntry
	nil,                              // 11: orbit.v1.StatusReport.BytesReceivedEntry
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 13: google.protobuf.Duration
}
var file_proto_orbit_v1_orbit_proto_depIdxs = []int32{
	12, // 0: orbit.v1.EchoRequest.sent_at:type_name -> google.protobuf.Timestamp
	12, // 1: orbit.v1.EchoResponse.sent_at:type_name -> google.protobuf.Timestamp
	12, // 2: orbit.v1.EchoResponse.received_at:type_name -> google.protobuf.Timestamp
	13, // 3: orbit.v1.FlowSpec.duration:type_name -> google.protobuf.Duration
	13, // 4: orbit.v1.FlowSpec.interval:type_name -> google.protobuf.Duration
	4,  // 5: orbit.v1.ProbeSchedule.east_west_flows:type_name -> orbit.v1.FlowSpec
	4,  // 6: orbit.v1.ProbeSchedule.north_south_flows:type_name -> orbit.v1.FlowSpec
	12, // 7: orbit.v1.ProbeSchedule.start_at:type_name -> google.protobuf.Timestamp
	10, // 8: orbit.v1.StatusReport.bytes_sent:type_name -> orbit.v1.StatusReport.BytesSentEntry
	11, // 9: orbit.v1.StatusReport.bytes_received:type_name -> orbit.v1.StatusReport.BytesReceivedEntry
	12, // 10: orbit.v1.StatusReport.reported_at:type_name -> google.protobuf.Timestamp
	12, // 11: orbit.v1.DataChunk.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 12: orbit.v1.OrbitService.Echo:input_type -> orbit.v1.EchoRequest
	2,  // 13: orbit.v1.OrbitService.Register:input_type -> orbit.v1.PeerRegistration
	5,  // 14: orbit.v1.OrbitService.AssignSchedule:input_type -> orbit.v1.ProbeSchedule
	7,  // 15: orbit.v1.OrbitService.ReportStatus:input_type -> orbit.v1.StatusReport
	9,  // 16: orbit.v1.OrbitService.StreamData:input_type -> orbit.v1.DataChunk
	1,  // 17: orbit.v1.OrbitService.Echo:output_type -> orbit.v1.EchoResponse
	3,  // 18: orbit.v1.OrbitService.Register:output_type -> orbit.v1.PeerRegistrationResponse
	6,  // 19: orbit.v1.OrbitService.AssignSchedule:output_type -> orbit.v1.ProbeScheduleResponse
	8,  // 20: orbit.v1.OrbitService.ReportStatus:output_type -> orbit.v1.StatusReportResponse
	9,  // 21: orbit.v1.OrbitService.StreamData:output_type -> orbit.v1.DataChunk
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_orbit_v1_orbit_proto_init() }
func file_proto_orbit_v1_orbit_proto_init() {
	if File_proto_orbit_v1_orbit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orbit_v1_orbit_proto_rawDesc), len(file_proto_orbit_v1_orbit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orbit_v1_orbit_proto_goTypes,
		DependencyIndexes: file_proto_orbit_v1_orbit_proto_depIdxs,
		MessageInfos:      file_proto_orbit_v1_orbit_proto_msgTypes,
	}.Build()
	File_proto_orbit_v1_orbit_proto = out.File
	file_proto_orbit_v1_orbit_proto_goTypes = nil
	file_proto_orbit_v1_orbit_proto_depIdxs = nil
}
